[package]
    authors=["Karolis Ramanauskas"]
    description="bioseq description in cargo.toml"
    edition="2024"
    license="GNU General Public License v3.0"
    name="bioseq"
    repository="https://github.com/karolisr/bioseq"
    rust-version="1.88"
    version="0.0.1"

[lib]
    crate-type=["lib"]
    name="bioseq"

[profile.dev]
    codegen-units=6       # 256
    debug=true            # true
    debug-assertions=true # true
    incremental=true      # true
    lto=false             # false
    opt-level=1           # 1
    overflow-checks=true  # true
    panic="abort"         # "unwind"
    rpath=false           # false
    strip=false           # false

[profile.release]
    codegen-units=1        # 16
    debug=false            # false
    debug-assertions=false # false
    incremental=false      # false
    lto=true               # false
    opt-level=3            # 3
    overflow-checks=true   # false
    panic="abort"          # "unwind"
    rpath=false            # false
    strip=true             # "none"
